"""empty message

Revision ID: 0b2930e4d4bd
Revises: c4b9e2f7a1d3
Create Date: 2026-08-28 14:35:54.508450

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '0b2930e4d4bd'
down_revision = 'c4b9e2f7a1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['removed_by'], ['username'])

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('BATCH_OPERATION', name='jobtype'),
               existing_nullable=False)

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('model_price', schema=None) as batch_op:
        batch_op.alter_column('pattern',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('prompt_price_per_1k',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('completion_price_per_1k',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_score'))
        batch_op.create_foreign_key(None, 'user', ['removed_by'], ['username'])

    with op.batch_alter_table('prompt_render_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_render_audit_version'))
        batch_op.create_index(batch_op.f('ix_prompt_render_audit_template_version_id'), ['template_version_id'], unique=False)

    with op.batch_alter_table('prompt_template_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_template_version_template'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_template_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_template_version_template'), ['template_id'], unique=False)

    with op.batch_alter_table('prompt_render_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_render_audit_template_version_id'))
        batch_op.create_index(batch_op.f('ix_prompt_render_audit_version'), ['template_version_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_post_score'), ['score'], unique=False)

    with op.batch_alter_table('model_price', schema=None) as batch_op:
        batch_op.alter_column('completion_price_per_1k',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('prompt_price_per_1k',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('pattern',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('BATCH_OPERATION', name='jobtype'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
