"""baseline schema

Revision ID: 359878740bb0
Revises:
Create Date: 2026-08-24 19:46:59.776493

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "359878740bb0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_endpoint_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_url", sa.String(length=255), nullable=False),
        sa.Column("default_model", sa.String(length=100), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_endpoint_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_endpoint_config_api_url"), ["api_url"], unique=True
        )

    op.create_table(
        "api_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_url", sa.String(length=255), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("last_fetched", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_url", "model_name"),
    )
    with op.batch_alter_table("api_model", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_model_api_url"), ["api_url"], unique=False
        )

    op.create_table(
        "generation_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "CREATE_SUBDEADDIT",
                "CREATE_USER",
                "CREATE_POST",
                "CREATE_COMMENT",
                "BATCH_OPERATION",
                "SCHEDULED_TASK",
                "CONTENT_CLEANUP",
                name="jobtype",
            ),
            nullable=False,
        ),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CREATE_SUBDEADDIT",
                "CREATE_USER",
                "CREATE_POST",
                "CREATE_COMMENT",
                "BATCH_OPERATION",
                "SCHEDULED_TASK",
                "CONTENT_CLEANUP",
                name="jobtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="jobstatus",
            ),
            nullable=True,
        ),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("estimated_completion", sa.DateTime(), nullable=True),
        sa.Column("rq_job_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_rq_job_id"), ["rq_job_id"], unique=True
        )

    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "subdeaddit",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("post_types", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("interests", sa.Text(), nullable=True),
        sa.Column("occupation", sa.String(length=100), nullable=True),
        sa.Column("education", sa.String(length=100), nullable=True),
        sa.Column("writing_style", sa.Text(), nullable=True),
        sa.Column("personality_traits", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("upvote_count", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("subdeaddit_name", sa.String(length=50), nullable=False),
        sa.Column("user", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("post_type", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["subdeaddit_name"],
            ["subdeaddit.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_post_model"), ["model"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_post_post_type"), ["post_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_post_subdeaddit_name"), ["subdeaddit_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_post_user"), ["user"], unique=False)

    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("upvote_count", sa.Integer(), nullable=True),
        sa.Column("user", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comment_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_comment_model"), ["model"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_comment_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_comment_post_id"), ["post_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_comment_upvote_count"), ["upvote_count"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_comment_user"), ["user"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_user"))
        batch_op.drop_index(batch_op.f("ix_comment_upvote_count"))
        batch_op.drop_index(batch_op.f("ix_comment_post_id"))
        batch_op.drop_index(batch_op.f("ix_comment_parent_id"))
        batch_op.drop_index(batch_op.f("ix_comment_model"))
        batch_op.drop_index(batch_op.f("ix_comment_created_at"))

    op.drop_table("comment")
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_user"))
        batch_op.drop_index(batch_op.f("ix_post_subdeaddit_name"))
        batch_op.drop_index(batch_op.f("ix_post_post_type"))
        batch_op.drop_index(batch_op.f("ix_post_model"))
        batch_op.drop_index(batch_op.f("ix_post_created_at"))

    op.drop_table("post")
    op.drop_table("user")
    op.drop_table("subdeaddit")
    op.drop_table("setting")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_rq_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_created_at"))

    op.drop_table("job")
    op.drop_table("generation_template")
    with op.batch_alter_table("api_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_model_api_url"))

    op.drop_table("api_model")
    with op.batch_alter_table("api_endpoint_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_endpoint_config_api_url"))

    op.drop_table("api_endpoint_config")
    # ### end Alembic commands ###
