"""composite indexes for feed and job queries

Revision ID: 5b2dab0b6816
Revises: 359878740bb0
Create Date: 2026-08-24 19:48:28.666124

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5b2dab0b6816"
down_revision = "359878740bb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.create_index(
            "ix_comment_post_id_created_at", ["post_id", "created_at"], unique=False
        )

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_status_priority", ["status", "priority"], unique=False
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(
            "ix_post_model_created_at", ["model", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_post_subdeaddit_name_created_at",
            ["subdeaddit_name", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index("ix_post_subdeaddit_name_created_at")
        batch_op.drop_index("ix_post_model_created_at")

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_status_priority")

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index("ix_comment_post_id_created_at")

    # ### end Alembic commands ###
