"""Image generation and secure local-media helpers.

Imports from this package only expose pure contracts and storage functions; no
application setup, filesystem access, or network work occurs at import time.
"""

from .client import (
    ImageAdapter,
    generate,
    get_adapter,
    register_adapter,
    reset_adapters,
    search_models,
    unregister_adapter,
    validate_model,
)
from .storage import (
    DownloadedImage,
    ImageTooLargeError,
    MalformedImageError,
    MediaPathTraversalError,
    MediaStorageError,
    ReconcileReport,
    StoredImage,
    UnsafeImageURLError,
    UnsupportedImageMIMEError,
    delete_variants,
    download_image,
    ensure_media_tree,
    media_root,
    reconcile_media,
    resolve_media_path,
    store_variants,
)
from .types import (
    Deadline,
    ImageAuthError,
    ImageContentPolicyError,
    ImageCredentialError,
    ImageGenerationResult,
    ImageProviderDisabledError,
    ImageProviderError,
    ImageProviderTransientError,
    ImageTimeoutError,
    ImageValidationError,
    MalformedImageResultError,
    ModelOption,
    ModelSearchResult,
    ModelValidation,
    UnknownImageProviderTypeError,
)

__all__ = [
    "Deadline",
    "DownloadedImage",
    "ImageAdapter",
    "ImageAuthError",
    "ImageContentPolicyError",
    "ImageCredentialError",
    "ImageGenerationResult",
    "ImageProviderDisabledError",
    "ImageProviderError",
    "ImageProviderTransientError",
    "ImageTimeoutError",
    "ImageTooLargeError",
    "ImageValidationError",
    "MalformedImageError",
    "MalformedImageResultError",
    "MediaPathTraversalError",
    "MediaStorageError",
    "ModelOption",
    "ModelSearchResult",
    "ModelValidation",
    "ReconcileReport",
    "StoredImage",
    "UnknownImageProviderTypeError",
    "UnsafeImageURLError",
    "UnsupportedImageMIMEError",
    "delete_variants",
    "download_image",
    "ensure_media_tree",
    "generate",
    "get_adapter",
    "media_root",
    "reconcile_media",
    "register_adapter",
    "reset_adapters",
    "resolve_media_path",
    "search_models",
    "store_variants",
    "unregister_adapter",
    "validate_model",
]
